targets:
    - name: boringssl-2016-02-12
      seeds:
          location: RUNDIR
          name: seeds
    - name: c-ares-CVE-2016-5180
      seeds:
          location: RUNDIR
          name: empty-seed
    - name: guetzli-2017-3-30
      seeds:
          location: FUZZER_TEST_SUITE
          name: seeds
      dict:
          location: FUZZER_TEST_SUITE
          name: jpeg.dict
      timeout: 2000+
    - name: harfbuzz-1.3.2
      seeds:
          location: RUNDIR
          name: seeds
    - name: json-2017-02-12
      seeds:
          location: RUNDIR
          name: seeds
    - name: lcms-2017-03-21
      seeds:
          location: FUZZER_TEST_SUITE
          name: seeds
    - name: libarchive-2017-01-04
      seeds:
          location: FUZZER_TEST_SUITE
          name: seeds
    - name: libxml2-v2.9.2
      seeds:
          location: RUNDIR
          name: empty-seed
      dict:
          location: RUNDIR
          name: xml.dict
    - name: llvm-libcxxabi-2017-01-27
      seeds:
          location: RUNDIR
          name: empty-seed
    - name: pcre2-10.00
      seeds:
          location: RUNDIR
          name: empty-seed
    - name: re2-2014-12-09
      seeds:
          location: RUNDIR
          name: empty-seed
    - name: sqlite-2016-11-14
      seeds:
          location: RUNDIR
          name: empty-seed
      dict:
          location: FUZZER_TEST_SUITE
          name: sql.dict
    - name: vorbis-2017-12-11
      seeds:
          location: FUZZER_TEST_SUITE
          name: seeds
    - name: woff2-2016-05-06
      seeds:
          location: RUNDIR
          name: seeds
